language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "Grace-Shredder-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # test the code
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: grace-shredder-1906
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: bwXkLQEcsKUjrGBKN3LdWGpgq0dVPdUH1pOrTimJw6VV3eRDkmwm69nPYgT77hXZQ/U1F1WQxFIfOxMUq4yRlhZSiMlZMRxh3Z6y7UV29PZPRCdeQvydQvkGoN1cv4WzLz5x9XPG3G2vfXzfhqQGW48OQaqvLFxabZtHeNmmPVp4dfsBypcnfY8o6BgGuGlzU3oL7vvp28qrqOpdqJ4zp200ErC9DCa4v7SFeZDZHBJP2RNuzR9LSaGrLSutA21f4Quk1CF1axdyOfg94lLqIRv14cl7dYfKrknp8fYik3PFoI+dnHyNxRpDX4Fe6GXFjdATOc1E5XErPxkQnEQ0lhOgOZLx6JrwOUBmoIBY6gAw4eTQFz8ZQTOvIb1yg9ks17vBfVFR8rMkbvsS2+ksRRS6UfHtklkD5qD/oWYBtTZfA88dH54n/mEDEKluXQG7qZOHMT9yRZn4zjdq2YUXD+uVJRYCgixputpllkVbtO61mofLjqorjt9dxOEQDWqB88l4yRiatUOfWKRXDW3kLM0am8sY2ouVf9jTWAaq29W8G5HkbrWgAfQ55w8yO+TFXM5uvrmH4Xq7iKgQWCjQkScbgetM+YzMhG745DdPZpJefQFrDhnUAA0KMdw37uqA6m1Wi+2nKRq35VJDnrxLm6zclEpP2ntAfmpYJ32Eww0=
